### ISSUE TITLE
Cloud SQL connection error in cloud shell 

### ISSUE THREAD

**Issue by Yash-Kavaiya** [googleapis/langchain-google-cloud-sql-mysql-python#75]
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1045, 'Cloud SQL MySQL: Automatic IAM authentication via the auth-proxy requires an IAM-authenticated user. Access denied for other users.\x00')
(Background on this error at: https://sqlalche.me/e/20/e3q8)

**Comment by averikitsch** [comment]
You will need to add your account or the service account as an authorized user of the database. You can find those instructions at https://cloud.google.com/sql/docs/mysql/add-manage-iam-users. Please reopen if you continue to experience this issue.
